---
- hosts: {{.Host}}
  remote_user: root
  gather_facts: no                                        # 默认执行setup模块，禁用此setup选项
  tasks:                                                    # 一个task 只能有一个模块元素
    - name:  sync kubernets directory to /etc
      copy:
        src: {{.DownloadDir}}/kubernetes
        dest: /etc
    - name: mkdir binary dir
      file:
        path: {{.Dir}}/log
        state: directory
        mode: '0755'
    - name: rsync bianry file to {{.Dir}}
      copy:
        src: {{.DownloadDir}}/kube-apiserver
        dest: {{.Dir}}
        mode: u+x
{{range $i, $v :=  .AllHost}}
- hosts: {{$v}}
  remote_user: root
  gather_facts: no                                        # 默认执行setup模块，禁用此setup选项
  tasks:                                                    # 一个task 只能有一个模块元素
    - name: create kube-apiserver service
      copy:
        src: {{GetCache}}/kube-apiserver.service_{{$v}}
        dest: /usr/lib/systemd/system/kube-apiserver.service
    - name: systemctl daemon-reload
      shell: systemctl daemon-reload
    - name: start apiserver
      service:
        name: kube-apiserver
        state: restarted
        enabled: yes
{{end}}