---
- hosts: {{.Host}}
  remote_user: root
  gather_facts: no                                        # 默认执行setup模块，禁用此setup选项
  tasks:                                                    # 一个task 只能有一个模块元素
    - name:  sync kubernets directory to /etc
      copy:
        src: {{.DownloadDir}}/kubernetes
        dest: /etc
    - name: mkdir binary dir
      file:
        path: {{.Dir}}/log
        state: directory
        mode: '0755'
    - name: rsync bianry file to  {{.Dir}}
      copy:
        src: {{.DownloadDir}}/kube-controller-manager
        dest: {{.Dir}}
        mode: u+x
    - name: create kube-controller-manager service
      copy:
        src: {{GetCache}}/kube-controller-manager.service
        dest: /usr/lib/systemd/system
    - name: systemctl daemon-reload
      shell: systemctl daemon-reload
    - name: start kube-controller-manager
      service:
        name: kube-controller-manager
        state: restarted
        enabled: yes