---
- hosts: {{.Host}}
  remote_user: root
  gather_facts: no                                        # 默认执行setup模块，禁用此setup选项
  tasks:                                                    # 一个task 只能有一个模块元素
    - name: sync kubernets directory to /etc
      copy:
        src: {{.DownloadDir}}/kubernetes
        dest: /etc
    - name: mkdir binary direcotry
      file:
        path: {{.Dir}}
        state: directory
        mode: '0755'
    - name: rsync etcd tar.gz to /tmp
      copy:
        src: {{.DownloadDir}}/{{.EtcdName}}
        dest: /tmp
    - name: unarchive etcd tar.gz
      unarchive:
        src: /tmp/{{.EtcdName}}
        dest: /tmp
    - name: mv file to {{.Dir}}
      shell:
        cmd: |
          /usr/bin/mv -f /tmp/etcd-*/etcd /tmp/etcd-*/etcdctl {{.Dir}}
          chmod +x {{.Dir}}/etcd*
    - name: create etcd service
      copy:
        src: {{GetCache}}/etcd.service
        dest: /usr/lib/systemd/system
    - name: daemon-reload
      shell: systemctl daemon-reload
    - name: stop etcd
      service:
        name: etcd
        state: stop
      ignore_errors: yes
    - name: rm {{.DataDir}}
      file:
        path: {{.DdataDir}}
        state: absent
      ignore_errors: yes
    - name: mkdir {{.DataDir}}
      file:
        path: {{.DataDir}}
        state: directory
{{range $i, $v :=  .AllHost}}
- hosts: {{$v}}
  remote_user: root
  gather_facts: no                                        # 默认执行setup模块，禁用此setup选项
  tasks:                                                    # 一个task 只能有一个模块元素
    - name: rsync etcd.config.yml to {{$v}}
      copy:
        src: {{GetCache}}/etcd.config.yml_{{$v}}
        dest: {{$.Dir}}/etcd.config.yml
    - name: start etcd
      service:
        name: etcd
        state: started
        enabled: yes
{{end}}