---
# generate etcd cert

- hosts: 127.0.0.1
  remote_user: root
  gather_facts: no
  tasks:
    - name: craate tempalte dir
      file:
        path: {{.DownloadDir}}/kubernetes/pki/etcd
        state: directory
    - name: generate etcd cert
      shell:
        cmd: |
#           /root/k8s-v1.23.9/cfssl_linux-amd64 gencert -initca etcd-ca-csr.json | /root/k8s-v1.23.9/cfssljson_linux-amd64 -bare /etc/kubernetes/pki/etcd/etcd-ca
           {{.DownloadDir}}/cfssl_* gencert -initca {{.DownloadDir}}/kubernetes/csr/etcd-ca-csr.json |  {{.DownloadDir}}/cfssljson_* \
               -bare {{.DownloadDir}}/kubernetes/pki/etcd/etcd-ca
#            /root/k8s-v1.23.9/cfssl_linux-amd64 gencert -ca=/etc/kubernetes/pki/etcd/etcd-ca.pem -ca-key=/etc/kubernetes/pki/etcd/etcd-ca-key.pem -config=ca-config.json -hostname=127.0.0.1,k8s-master01,k8s-master02,k8s-master03,192.168.58.129,192.168.58.130,192.168.58.131 -profile=kubernetes etcd-csr.json |/root/k8s-v1.23.9/cfssljson_linux-amd64 -bare /etc/kubernetes/pki/etcd/etcd
           {{.DownloadDir}}/cfssl_*  gencert -ca={{.DownloadDir}}/kubernetes/pki/etcd/etcd-ca.pem \
               -ca-key={{.DownloadDir}}/kubernetes/pki/etcd/etcd-ca-key.pem \
               -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
               -hostname={{.Allhost}} \
               -profile=kubernetes \
               {{.DownloadDir}}/kubernetes/csr/etcd-csr.json | {{.DownloadDir}}/cfssljson_* \
               -bare {{.DownloadDir}}/kubernetes/pki/etcd/etcd

---
# generate apiserver cert
- hosts: 127.0.0.1
  remote_user: root
  gather_facts: no
  tasks:
    - name: craate tempalte dir
      file:
        path: {{.DownloadDir}}/kubernetes/pki/
        state: directory
    - name: generate ca cert
      shell:
        cmd: |
#          /root/k8s-v1.23.9/cfssl_linux-amd64 gencert -initca ca-csr.json |/root/k8s-v1.23.9/cfssljson_linux-amd64 -bare /etc/kubernetes/pki/ca
           {{.DownloadDir}}/cfssl_* gencert -initca {{.DownloadDir}}/kubernetes/csr/ca-csr.json |  {{.DownloadDir}}/cfssljson_* \
           -bare {{.DownloadDir}}/kubernetes/pki/ca
    - name: generate apiserver cert
      shell:
        cmd: |
#          /root/k8s-v1.23.9/cfssl_linux-amd64 gencert -ca=/etc/kubernetes/pki/etcd/etcd-ca.pem -ca-key=/etc/kubernetes/pki/etcd/etcd-ca-key.pem -config=ca-config.json -hostname=127.0.0.1,k8s-master01,k8s-master02,k8s-master03,192.168.58.129,192.168.58.130,192.168.58.131 -profile=kubernetes etcd-csr.json |/root/k8s-v1.23.9/cfssljson_linux-amd64 -bare /etc/kubernetes/pki/etcd/etcd
           {{.DownloadDir}}/cfssl_*  gencert -ca={{.DownloadDir}}/kubernetes/pki/ca.pem \
           -ca-key={{.DownloadDir}}/kubernetes/pki/ca-key.pem \
           -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
           -hostname={{.Allhost}} \
           -profile=kubernetes \
           {{.DownloadDir}}/kubernetes/csr/apiserver-csr.json | {{.DownloadDir}}/cfssljson_* \
           -bare {{.DownloadDir}}/kubernetes/pki/apiserver

---
# generate front-proxy cert
- hosts: 127.0.0.1
  remote_user: root
  gather_facts: no
  tasks:
    - name: craate tempalte dir
      file:
        path: {{.DownloadDir}}/kubernetes/pki
        state: directory
    - name: generate ca cert
      shell:
        cmd: |
  #         /root/k8s-v1.23.9/cfssl_linux-amd64 gencert -initca front-proxy-ca-csr.json |/root/k8s-v1.23.9/cfssljson_linux-amd64 -bare /etc/kubernetes/pki/front-proxy-ca
           {{.DownloadDir}}/cfssl_* gencert -initca {{.DownloadDir}}/kubernetes/csr/front-proxy-ca-csr.json |  {{.DownloadDir}}/cfssljson_* \
          -bare {{.DownloadDir}}/kubernetes/pki/front-proxy-ca
    - name: generate  front-proxy  cert
      shell:
        cmd: |
#          /root/k8s-v1.23.9/cfssl_linux-amd64 gencert -ca=/etc/kubernetes/pki/front-proxy-ca.pem -ca-key=/etc/kubernetes/pki/front-proxy-ca-key.pem -config=ca-config.json  -profile=kubernetes front-proxy-client-csr.json |/root/k8s-v1.23.9/cfssljson_linux-amd64 -bare /etc/kubernetes/pki/front-proxy-client
           {{.DownloadDir}}/cfssl_*  gencert -ca={{.DownloadDir}}/kubernetes/pki/front-proxy-ca.pem \
           -ca-key={{.DownloadDir}}/kubernetes/pki/front-proxy-ca-key.pem \
           -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
           -profile=kubernetes \
           {{.DownloadDir}}/kubernetes/csr/front-proxy-client-csr.json | {{.DownloadDir}}/cfssljson_* \
           -bare {{.DownloadDir}}/kubernetes/pki/front-proxy-client

---
# generate controller-manager cert
- hosts: 127.0.0.1
  remote_user: root
  gather_facts: no
  tasks:
    - name: craate tempalte dir
      file:
        path: {{.DownloadDir}}/kubernetes/pki/
        state: directory
    - name: generate controller-manager cert
      shell:
        cmd: |
#          /root/k8s-v1.23.9/cfssl_linux-amd64 gencert -ca=/etc/kubernetes/pki/ca.pem -ca-key=/etc/kubernetes/pki/ca-key.pem  -config=ca-config.json -profile=kubernetes manager-csr.json |/root/k8s-v1.23.9/cfssljson_linux-amd64 -bare /etc/kubernetes/pki/controller-manager
           {{.DownloadDir}}/cfssl_*  gencert -ca={{.DownloadDir}}/kubernetes/pki/ca.pem \
           -ca-key={{.DownloadDir}}/kubernetes/pki/ca-key.pem \
           -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
           -profile=kubernetes \
           {{.DownloadDir}}/kubernetes/csr/manager-csr.json | {{.DownloadDir}}/cfssljson_* \
           -bare {{.DownloadDir}}/kubernetes/pki/controller-manager
