---
# generate cert

- hosts: 127.0.0.1
  remote_user: root
  gather_facts: no
  tasks:
    - name: craate tempalte dir
      file:
        path: {{.DownloadDir}}/kubernetes/pki/etcd
        state: directory
    - name: generate etcd cert
      shell:
        cmd: |
           {{.DownloadDir}}/cfssl_* gencert -initca {{.DownloadDir}}/kubernetes/csr/etcd-ca-csr.json |  {{.DownloadDir}}/cfssljson_* \
            -bare {{.DownloadDir}}/kubernetes/pki/etcd/etcd-ca
           {{.DownloadDir}}/cfssl_*  gencert -ca={{.DownloadDir}}/kubernetes/pki/etcd/etcd-ca.pem \
            -ca-key={{.DownloadDir}}/kubernetes/pki/etcd/etcd-ca-key.pem \
            -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
            -hostname={{.Etcdhost}} \
            -profile=kubernetes \
            {{.DownloadDir}}/kubernetes/csr/etcd-csr.json | {{.DownloadDir}}/cfssljson_* \
            -bare {{.DownloadDir}}/kubernetes/pki/etcd/etcd
    - name: generate ca cert
      shell:
        cmd: |
          {{.DownloadDir}}/cfssl_* gencert -initca {{.DownloadDir}}/kubernetes/csr/ca-csr.json |  {{.DownloadDir}}/cfssljson_* \
            -bare {{.DownloadDir}}/kubernetes/pki/ca
    - name: generate apiserver cert
      shell:
        cmd: |
          {{.DownloadDir}}/cfssl_*  gencert -ca={{.DownloadDir}}/kubernetes/pki/ca.pem \
            -ca-key={{.DownloadDir}}/kubernetes/pki/ca-key.pem \
            -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
            -hostname={{.Allhost}} \
            -profile=kubernetes \
            {{.DownloadDir}}/kubernetes/csr/apiserver-csr.json | {{.DownloadDir}}/cfssljson_* \
            -bare {{.DownloadDir}}/kubernetes/pki/apiserver
    - name: generate ca cert
      shell:
        cmd: |
           {{.DownloadDir}}/cfssl_* gencert -initca {{.DownloadDir}}/kubernetes/csr/front-proxy-ca-csr.json |  {{.DownloadDir}}/cfssljson_* \
            -bare {{.DownloadDir}}/kubernetes/pki/front-proxy-ca
    - name: generate  front-proxy  cert
      shell:
        cmd: |
           {{.DownloadDir}}/cfssl_*  gencert -ca={{.DownloadDir}}/kubernetes/pki/front-proxy-ca.pem \
            -ca-key={{.DownloadDir}}/kubernetes/pki/front-proxy-ca-key.pem \
            -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
            -profile=kubernetes \
            {{.DownloadDir}}/kubernetes/csr/front-proxy-client-csr.json | {{.DownloadDir}}/cfssljson_* \
            -bare {{.DownloadDir}}/kubernetes/pki/front-proxy-client
    - name: generate controller-manager cert
      shell:
        cmd: |
           {{.DownloadDir}}/cfssl_*  gencert -ca={{.DownloadDir}}/kubernetes/pki/ca.pem \
            -ca-key={{.DownloadDir}}/kubernetes/pki/ca-key.pem \
            -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
            -profile=kubernetes \
            {{.DownloadDir}}/kubernetes/csr/manager-csr.json | {{.DownloadDir}}/cfssljson_* \
             -bare {{.DownloadDir}}/kubernetes/pki/controller-manager
    - name: genrate scheduler cert
      shell:
        cmd: |
          {{.DownloadDir}}/cfssl_* gencert -ca={{.DownloadDir}}/kubernetes/pki/ca.pem \
           -ca-key={{.DownloadDir}}/kubernetes/pki/ca-key.pem \
           -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
           -profile=kubernetes \
           {{.DownloadDir}}/kubernetes/csr/scheduler-csr.json |{{.DownloadDir}}/cfssljson_* \
           -bare  {{.DownloadDir}}/kubernetes/pki/scheduler
    - name: genrate admin cert
      shell:
        cmd: |
          {{.DownloadDir}}/cfssl_* gencert -ca={{.DownloadDir}}/kubernetes/pki/ca.pem \
            -ca-key={{.DownloadDir}}/kubernetes/pki/ca-key.pem \
            -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
            -profile=kubernetes {{.DownloadDir}}/kubernetes/csr/admin-csr.json |{{.DownloadDir}}/cfssljson_* \
            -bare {{.DownloadDir}}/kubernetes/pki/admin
    - name: genrate kube-proxy cert
      shell:
        cmd: |
          {{.DownloadDir}}/cfssl_* gencert -ca={{.DownloadDir}}/kubernetes/pki/ca.pem \
            -ca-key={{.DownloadDir}}/kubernetes/pki/ca-key.pem \
            -config={{.DownloadDir}}/kubernetes/csr/ca-config.json \
            -profile=kubernetes {{.DownloadDir}}/kubernetes/csr/kube-proxy-csr.json |{{.DownloadDir}}/cfssljson_* \
            -bare {{.DownloadDir}}/kubernetes/pki/kube-proxy