---
- hosts: {{.Host}}
  remote_user: root
  gather_facts: no                                        # 默认执行setup模块，禁用此setup选项
  tasks:                                                    # 一个task 只能有一个模块元素
    - name:
      yum:
        - haproxy
      state: present
    - name: config
      copy:
        src: /tmp/haproxy.cfg
        dest: /etc/haproxy
    - name: start docker
      service:
        name: haproxy
        state: started
        enabled: yes