---
- hosts: {{.Host}}
  remote_user: root
  gather_facts: no                                        # 默认执行setup模块，禁用此setup选项
  tasks:                                                    # 一个task 只能有一个模块元素
    - name:  add yum-repo
      shell: yum-config-manager --add-repo {{.YumRepo}} && yum makecache fast
    - name: install containerd
      yum:
        name:
          - containerd.io
        state: present
    - name: mkdir {{.DataRoot}}
      file:
        path: {{.DataRoot}}
        state: directory
        mode: '0755'
    - name: genrate config
      shell:
        cmd: |
          containerd config default > /etc/containerd/config.toml
          sed -i 's@root = "/var/lib/containerd"@root = "{{.DataRoot}}"@g' /etc/containerd/config.toml
          sed -i 's@SystemdCgroup = false@SystemdCgroup = true@g' /etc/containerd/config.toml
          sed -i 's@sandbox_image = ".*"@sandbox_image = "{{.SandboxImage}}"@g' /etc/containerd/config.toml
          sed -i '/\[plugins."io.containerd.grpc.v1.cri".registry.mirrors\]/a [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]' /etc/containerd/config.toml
          sed -i '/\[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"\]/a endpoint = \["{{.RegistryMirrors}}"\]' /etc/containerd/config.toml
    - name: start containerd
      service:
        name: containerd
        state: restarted
        enabled: yes