---
# generate kubconfig

- hosts: 127.0.0.1
  remote_user: root
  gather_facts: no
  tasks:
    - name: generate kube-proxy kubeconfig
      shell:
        cmd: |
          {{.DownloadDir}}/kubectl config set-cluster kubernetes \
           --certificate-authority={{.DownloadDir}}/kubernetes/pki/ca.pem \
           --embed-certs=true --server=https://{{.Vip}}:{{.Port}} \
           --kubeconfig={{.DownloadDir}}/kubernetes/kube-proxy.kubeconfig
          {{.DownloadDir}}/kubectl config set-context kubernetes  \
           --cluster=kubernetes --user=kubernetes \
           --kubeconfig={{.DownloadDir}}/kubernetes/kube-proxy.kubeconfig
          {{.DownloadDir}}/kubectl config set-credentials kubernetes  \
           --token={{.Token}} \
           --kubeconfig={{.DownloadDir}}/kubernetes/kube-proxy.kubeconfig
          {{.DownloadDir}}/kubectl config use-context kubernetes \
           --kubeconfig={{.DownloadDir}}/kubernetes/kube-proxy.kubeconfig