---
- hosts: {{.Host}}
  remote_user: root
    gather_facts: no                                        # 默认执行setup模块，禁用此setup选项
    tasks:                                                    # 一个task 只能有一个模块元素
      - name: copy binary file
        copy:
          src: {{.DownloadDir}}/kubelet
          dest: {{.Dir}}
          mode: "0755"
      - name: copy service
        copy:
          src: {{GetCache}}/kubelet.service
          dest: /usr/lib/systemd/system
      - name: mkdir kubernetes
        file:
          path: /etc/kubernetes/manifests
          state: directory
          mode: "0755"
      - name: mkdir pki
        file:
          path: /etc/kubernetes/pki
          state: directory
          mode: "0755"
      - name: mkdir log
        file:
          path: {{.Dir}}/log
          state: directory
          mode: "0755"
      - name: copy bootstrap config
        copy:
          src: {{.DownloadDir}}/kubernetes/bootstrap-kubelet.kubeconfig
          dest: /etc/kubernetes
      - name: copy kubelet config
        copy:
          src: {{GetCache}}/kubelet-conf.yml
          dest: {{.Dir}}
      - name: copy ca pem
        copy:
          src:  {{.DownloadDir}}/kubernetes/pki/ca.pem
          dest: /etc/kubernetes/pki
      - name: copy ca key
        copy:
          src:  {{.DownloadDir}}/kubernetes/pki/ca-key.pem
          dest: /etc/kubernetes/pki
      - name: copy front-proxy-ca pem
        copy:
          src:  {{.DownloadDir}}/kubernetes/pki/front-proxy-ca.pem
          dest: /etc/kubernetes/pki
      - name: systemctl daeme-reload
        shell: systemctl daemon-reload
      - name: start kubelet
        service:
          name: kubelet
          state: started
          enabled: yes