k8s:
  master:
    components:
      - name: etcd
        hosts:
          - 192.168.58.129
          - 192.168.58.130
          - 192.168.58.131
        dir: /opt/etcd
        dataDir: /data/etcd
      - name: api-server
        hosts:
          - 192.168.58.129
          - 192.168.58.130
          - 192.168.58.131
        dir: /opt/api-server
      - name: scheduler
        hosts:
          - 192.168.58.129
          - 192.168.58.130
          - 192.168.58.131
        dir: /opt/scheduler
      - name: controller-manager
        hosts:
          - 192.168.58.129
          - 192.168.58.130
          - 192.168.58.131
        dir: /opt/controller-manager
  node:
    hosts:
      - 192.168.58.129
      - 192.168.58.130
      - 192.168.58.131
    components:
      - name: kubelet
        dir: /opt/kubelet
      - name: kubproxy
        dir: /opt/kube-proxy
  plugin:
    - name: coreDns
      dns: 172.16.0.10
#    如果使用calico插件，注释掉flannel部分，反之亦然
#    - name: calico
#      podCIDR: 10.100.0.0/16
#      calicoUrl: https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico-typha.yaml
    - name: flannel
      podCIDR: 10.100.0.0/16
      flannelUrl: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  CIDR:
    serviceCIDR: 172.16.0.0/16
  certificate: 876000h

# k8s v1.24.0 版本后不支持dockershim
# docker 和 containerd 保留一个
cri:
#  docker:
#    yumRepo: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
#    dataRoot: /var/lib/docker
#    registryMirrors: https://mvaav0ar.mirror.aliyuncs.com
#    pod-infra-container-image: registry.aliyuncs.com/google_containers/pause:3.5
  containerd:
    yumRepo: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    dataRoot: /var/lib/containerd
    registryMirrors:  https://mvaav0ar.mirror.aliyuncs.com
    sandboxImage: registry.aliyuncs.com/google_containers/pause:3.5

haproxy:
  hosts:
    - 192.168.58.129
    - 192.168.58.130
    - 192.168.58.131
  frontendPort: 16443

keepalived:
  hosts:
    - 192.168.58.129
    - 192.168.58.130
    - 192.168.58.131
  vip: 192.168.58.110
  interface: ens33

packages:
  downloadDir: /tmp/packages
  url:
    - https://dl.k8s.io/v1.23.9/bin/linux/amd64/kube-controller-manager
    - https://dl.k8s.io/v1.23.9/bin/linux/amd64/kube-apiserver
    - https://dl.k8s.io/v1.23.9/bin/linux/amd64/kube-scheduler
    - https://github.com/etcd-io/etcd/releases/download/v3.4.20/etcd-v3.4.20-linux-amd64.tar.gz
    - https://dl.k8s.io/v1.23.9/bin/linux/amd64/kube-proxy
    - https://dl.k8s.io/v1.23.9/bin/linux/amd64/kubelet
    - https://dl.k8s.io/v1.23.9/bin/linux/amd64/kubectl
    - https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
    - https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64